name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Images
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: |
            wetcoffeeBean/voting-app-vote:latest
            wetcoffeeBean/voting-app-vote:1
            wetcoffeeBean/voting-app-result:latest
            wetcoffeeBean/voting-app-result:1
            wetcoffeeBean/voting-app-worker:latest
            wetcoffeeBean/voting-app-worker:1
