---
name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4
#        sdds

      - name: Build with Docker Compose
        run: export COMPOSE_PROJECT_NAME=voting-app && docker compose -f docker-compose.yml build

      - name: Push images
        if: github.event_name != 'pull_request'
        run:
          docker tag ${COMPOSE_PROJECT_NAME}_vote:latest wetcoffeeBean/voting-app-vote:1 &&
          docker tag ${COMPOSE_PROJECT_NAME}_result:latest wetcoffeeBean/voting-app-result:1 &&
          docker tag ${COMPOSE_PROJECT_NAME}_worker:latest wetcoffeeBean/voting-app-worker:1
          
          docker push wetcoffeeBean/voting-app-vote:1 &&
          docker push wetcoffeeBean/voting-app-result:1 &&
          docker push v/voting-app-worker:1