---
name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    environment: dev
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Docker Compose
        run: docker compose build

      - name: Push images
        if: github.event_name != 'pull_request'
        run:
          docker tag voting_app:latest wetcoffeeBean/votingApp:1
          docker push wetcoffeeBean/votingApp:1